dist: trusty
language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.18"
  - "5.10"
before_install:
  - cpanm -nq Devel::Cover::Report::Coveralls
script:
  perl Build.PL && ./Build build && cover -test
after_success:
  - cover -report coveralls
